// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2, arg3) {
  return window['go']['wailshandler']['FileHandler']['CreateFile'](arg1, arg2, arg3);
}

export function CreateNote(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['CreateNote'](arg1, arg2);
}

export function DeletePath(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['DeletePath'](arg1, arg2);
}

export function ListTree(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['ListTree'](arg1, arg2);
}

export function ReadFile(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['ReadFile'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['wailshandler']['FileHandler']['RenamePath'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['wailshandler']['FileHandler']['WriteFile'](arg1, arg2, arg3);
}
