// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {file} from '../models';

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeletePath(arg1:string,arg2:string):Promise<void>;

export function ListTree(arg1:string,arg2:string):Promise<Array<file.FileEntry>>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
