// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePlugin(arg1) {
  return window['go']['wailshandler']['PluginCatalogHandler']['DeletePlugin'](arg1);
}

export function GetPluginsDirectory() {
  return window['go']['wailshandler']['PluginCatalogHandler']['GetPluginsDirectory']();
}

export function ImportPluginArchive(arg1) {
  return window['go']['wailshandler']['PluginCatalogHandler']['ImportPluginArchive'](arg1);
}

export function ListPlugins() {
  return window['go']['wailshandler']['PluginCatalogHandler']['ListPlugins']();
}

export function PickPluginArchive() {
  return window['go']['wailshandler']['PluginCatalogHandler']['PickPluginArchive']();
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['wailshandler']['PluginCatalogHandler']['SetPluginEnabled'](arg1, arg2);
}
