// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPluginProcess(arg1:string):Promise<void>;

export function CopyPluginAsset(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPluginData(arg1:string,arg2:string):Promise<string>;

export function LoadPluginSource(arg1:string):Promise<string>;

export function PickPluginFiles(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<string>>;

export function SetPluginData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartPluginProcess(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:string,arg7:string):Promise<void>;
