// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPluginProcess(arg1) {
  return window['go']['wailshandler']['PluginRuntimeHandler']['CancelPluginProcess'](arg1);
}

export function CopyPluginAsset(arg1, arg2, arg3) {
  return window['go']['wailshandler']['PluginRuntimeHandler']['CopyPluginAsset'](arg1, arg2, arg3);
}

export function GetPluginData(arg1, arg2) {
  return window['go']['wailshandler']['PluginRuntimeHandler']['GetPluginData'](arg1, arg2);
}

export function LoadPluginSource(arg1) {
  return window['go']['wailshandler']['PluginRuntimeHandler']['LoadPluginSource'](arg1);
}

export function PickPluginFiles(arg1, arg2, arg3) {
  return window['go']['wailshandler']['PluginRuntimeHandler']['PickPluginFiles'](arg1, arg2, arg3);
}

export function SetPluginData(arg1, arg2, arg3) {
  return window['go']['wailshandler']['PluginRuntimeHandler']['SetPluginData'](arg1, arg2, arg3);
}

export function StartPluginProcess(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailshandler']['PluginRuntimeHandler']['StartPluginProcess'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
