// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';

export function DeletePlugin(arg1:string):Promise<void>;

export function GetPluginsDirectory():Promise<string>;

export function ImportPluginArchive(arg1:string):Promise<plugin.Plugin>;

export function ListPlugins():Promise<Array<plugin.Plugin>>;

export function PickPluginArchive():Promise<string>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;
